{% set version = "0.4.1" %}

package:
  name: datasci-bricoletc
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/d/datasci-bricoletc/datasci_bricoletc-{{ version }}.tar.gz
  sha256: fcf3b6800eccee3f370343a7cc5e3ea37912f061705089885660afd2d3d76d75

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling >=1.26.1
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - datasci
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Utilities for basic data science
  home: https://github.com/bricoletc/datasci
  dev_url: https://github.com/bricoletc/datasci
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kbseah
